/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front_package.Bill;

import front_package.Front_page;
//import front_package.Front_page;
import front_package.login.login;
import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Date;

//import front_package.pos_frontpage.Pos_frontpage;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import SRS.srs;

/**
 *
 * @author dell
 */
public class Bill_board extends javax.swing.JFrame {

    /**
     * Creates new form Bill_board
     */
    public Bill_board() {
        initComponents();
        setSize(1970, 1080);
        this.setResizable(true);
        this.setAlwaysOnTop(false);
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int)tk.getScreenSize().getWidth();
        int ysize = (int)tk.getScreenSize().getHeight();
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        this.setSize(xsize, ysize);
       
        jTable2.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        jTable2.getTableHeader().setOpaque(false);
        jTable2.getTableHeader().setBackground(new Color(204, 204, 255));
        jTable2.getTableHeader().setForeground(new Color(0, 0, 0));
        jTable2.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        total_label = new javax.swing.JLabel();
        total_textfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cancel_btn = new javax.swing.JButton();
        generate_bill_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        product_id_label = new javax.swing.JLabel();
        quantity_label = new javax.swing.JLabel();
        quantity_textfield = new javax.swing.JTextField();
        product_id_textfield = new javax.swing.JTextField();
        add_to_bill_btn = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1.setPreferredSize(new java.awt.Dimension(132, 22));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bill-Board");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153, 150));
        jPanel1.setLayout(null);

        logout.setBackground(new java.awt.Color(153, 153, 153));
        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setText("Logout");
        logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(1280, 10, 99, 40);

        jPanel2.setBackground(new java.awt.Color(204, 102, 255, 70));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 300));

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                
            },
            new String [] {
                "Product ID", "Product Name", "Product Price", "Product Quantity"
            }
        ));
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setGridColor(new java.awt.Color(0, 0, 0));
        jTable2.setRowHeight(30);
        jTable2.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable2.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable2.setShowGrid(true);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable2);

        total_label.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        total_label.setText("Total ₹");

        total_textfield.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        total_textfield.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        total_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_textfieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText(" ");

        cancel_btn.setBackground(new java.awt.Color(255, 204, 153));
        cancel_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancel_btn.setText("Cancel");
        cancel_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cancel_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        generate_bill_btn.setBackground(new java.awt.Color(255, 204, 153));
        generate_bill_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        generate_bill_btn.setText("Generate BILL");
        generate_bill_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        generate_bill_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generate_bill_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_bill_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                        .addComponent(total_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(total_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(316, 316, 316)
                        .addComponent(generate_bill_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(total_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(total_label))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generate_bill_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 60, 1360, 450);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bill Board");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(610, 0, 213, 56);
 
        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 80, 1400, 530);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);

        product_id_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        product_id_label.setText("Enter Product ID");
        getContentPane().add(product_id_label);
        product_id_label.setBounds(500, 630, 160, 50);

        quantity_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        quantity_label.setText("Enter Quantity");
        getContentPane().add(quantity_label);
        quantity_label.setBounds(500, 710, 160, 50);

        quantity_textfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        quantity_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        quantity_textfield.setPreferredSize(new java.awt.Dimension(132, 22));
        quantity_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantity_textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(quantity_textfield);
        quantity_textfield.setBounds(700, 710, 180, 50);

        product_id_textfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        product_id_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        product_id_textfield.setPreferredSize(new java.awt.Dimension(132, 22));
        product_id_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_id_textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(product_id_textfield);
        product_id_textfield.setBounds(700, 630, 180, 50);

        add_to_bill_btn.setBackground(new java.awt.Color(255, 204, 153));
        add_to_bill_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add_to_bill_btn.setText("ADD TO BILL");
        add_to_bill_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_to_bill_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_to_bill_btnActionPerformed(evt);
            }
        });
        getContentPane().add(add_to_bill_btn);
        add_to_bill_btn.setBounds(920, 670, 101, 50);
       

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Logout Successfull");
        if(evt.getSource() == logout){
            get_frontpage();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void quantity_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantity_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantity_textfieldActionPerformed

    private void product_id_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_id_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_id_textfieldActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
    	JOptionPane.showMessageDialog(rootPane, "Bill Cancelled");
    	reset_table();
    	
    }//GEN-LAST:event_cancel_btnActionPerformed
    public void make_bill()
    {
    	jTextArea1.setText("");
    	System.out.println("1 times");
//    	jTextArea1.setText(jTextArea1.getText()+da
    	
    	Date current_date=new Date();
    	jTextArea1.setText(jTextArea1.getText()+"  Date:"+current_date);
    	jTextArea1.setText(jTextArea1.getText()+"\n===========================================================================");
    	jTextArea1.setText(jTextArea1.getText()+"\n\t\t   AAA POS APP \n");
    	jTextArea1.setText(jTextArea1.getText()+"\n\t Indira College Of Commerce And Science  \n");
    	jTextArea1.setText(jTextArea1.getText()+"\nProduct ID "+"\t"+"Product Name"+" \t\t"+"Price"+ "\t"+" Quantity  \n");
    	jTextArea1.setText(jTextArea1.getText()+"\n===========================================================================\n");
    	for(int j=0;j<jTable2.getRowCount();j++)
    	{
    		String id=jTable2.getValueAt(j, 0).toString();
    		String name=jTable2.getValueAt(j, 1).toString();
    		String price=jTable2.getValueAt(j, 2).toString();
    		String quantity=jTable2.getValueAt(j, 3).toString();
    		jTextArea1.setText(jTextArea1.getText()+"\n"+"   "+id+"\t"+String.format("%-20s",name)+"\t"+price+"\t"+quantity+"   \n");
//    		jTextArea1.setText(jTextArea1.getText()+"\n"+id+" \t"+name+"\t"+price+" "+quantity+" \n");
    	}
    	String grand_total=total_textfield.getText().toString();
    	jTextArea1.setText(jTextArea1.getText()+"\n===========================================================================\n\n");
    	jTextArea1.setText(jTextArea1.getText()+"\t\t\t\tTotal: "+grand_total+"\n");
    	jTextArea1.setText(jTextArea1.getText()+"\n===========================================================================\n");
    	jTextArea1.setText(jTextArea1.getText()+"\t\t********************* \n");
    	jTextArea1.setText(jTextArea1.getText()+"\t\t     THANK YOU \n");
    	jTextArea1.setText(jTextArea1.getText()+"\t\t********************* \n");
    }
    private void generate_bill_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_bill_btnActionPerformed
        // TODO add your handling code here:
     	
    	if(login.LOGIN==1)
    	{
    		idquantity[] ledger=new idquantity[jTable2.getRowCount()];
    		
    		try 
    		{
    			System.out.println(jTable2.getRowCount());  //initial row count
    			if(jTable2.getRowCount()==0)
    			{
    				JOptionPane.showMessageDialog(rootPane,"Bill cannot be empty");
    				reset_table();
    			}
    			else
    			{
    				jTextArea1.setText(" ");
    				make_bill();
    				System.out.println("22 times");
    				System.out.println(jTextArea1.getText());
    				print=jTextArea1.print();
    			
    			if(print)
    			{
    				String url="jdbc:postgresql://localhost/POS_APP";
    		    	String user="postgres";
    		    	String password="postgres";
    		    	
    		    	String sql_update="UPDATE inventory SET actual_quantity=actual_quantity-? WHERE id=?";
    		    	PreparedStatement psVupdate=null;
    		    	try(Connection con=DriverManager.getConnection(url,user,password))
    		    	{
    		    		System.out.println("Connection Successfull");
    		    		psVupdate=con.prepareStatement(sql_update);
    		    		for(int l=0;l<jTable2.getRowCount();l++)
    	    		{
    		    			System.out.println(jTable2.getRowCount());
    		    		ledger[l]=new idquantity(jTable2.getValueAt(l,0).toString(),Integer.parseInt(jTable2.getValueAt(l,3).toString()));
    		    		psVupdate.setInt(1,ledger[l].quantity);
    		    		System.out.println("1st parameter passed"+ledger[l].quantity);
    		    		psVupdate.setString(2,ledger[l].id);
    		    		System.out.println("2nd parameter passed"+ledger[l].id);
    		    		if(psVupdate.executeUpdate()!=0)
    		    		{
    		    			srs run=new srs();
    		    			run.run_srs();
    		    		 System.out.println("Update DONE");
    		    		 reset_table();
    		    		}
    		    		else
    		    		{
    		    			JOptionPane.showMessageDialog(rootPane,"Something went wrong");
    		    			reset_table();
    		    		}
    	    		}
    		    		con.close();
    		    	}
    		    	catch(SQLException eX)
    		    	{
    		    		System.out.println(eX);
    		    	}
    		    	
    			}
    		}}
    		catch(Exception ex)
    		{
    			
    		}
    	}
    	else
    	{
    		JOptionPane.showMessageDialog(rootPane, "Please Login to continue");
    		get_frontpage();
    	}
    }//GEN-LAST:event_generate_bill_btnActionPerformed

    private void add_to_bill_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_to_bill_btnActionPerformed
        // TODO add your handling code here:
    	if(login.LOGIN==1)  //check login
    	{
    	String url="jdbc:postgresql://localhost/POS_APP";   //connection credentials
    	String user="postgres";
    	String password="postgres";
    	
    	String sql_select="Select id,name,price,actual_quantity FROM inventory where id=?";  //querry
    	//String sql_cust="INSERT INTO(name,address,m_no) customer values(?,?,?)";
    
    	try(Connection con=DriverManager.getConnection(url,user,password))  
    	{
    		PreparedStatement pss=con.prepareStatement(sql_select);     
    		//Statement stmt=con.createStatement();
    		System.out.println("1");
    		if(evt.getSource() == add_to_bill_btn)               //button clicked
    		{
    			System.out.println(product_id_textfield.getText());
    			pss.setString(1,product_id_textfield.getText());
    			ResultSet rs=pss.executeQuery();
    			System.out.println("2");
    		if(rs.next())
    			{	
    			if((quantity_textfield.getText()).isEmpty())
    			{
    				JOptionPane.showMessageDialog(rootPane,"Quantity cannot be blank");
    			}
    			else {
    				
    				String add_quantity=quantity_textfield.getText();
    				float[] sub_total=new float[30];
    			System.out.println("3 "+i);
    	    	String p_id=(rs.getString("id"));
    	    	System.out.println("4 "+i);
    	    	String p_name=(rs.getString("name"));
    	    	System.out.println("5 "+i);
    	    	Float price=(rs.getFloat("price"));
    	    	String p_price=(Double.toString(rs.getDouble("price")));
    	    	System.out.println("6 "+i);
    	    	//String actual_quantity=(Integer.toString(rs.getInt("actual_quantity")));
    	    	System.out.println("7 "+i);
    	    	//String cat=rs.getString("category");
    	    	System.out.println("8 "+i);
    	    	System.out.println("9 "+i);
    	    	int q=Integer.parseInt(add_quantity);
    	    	System.out.println("10 "+i);
    	    	sub_total[i]=price*q;
    	    	System.out.println("11 "+i);
    	    	System.out.println("12 "+i);
    	    	SUM=SUM+sub_total[i];
    	    	total_textfield.setText(Float.toString(SUM));
    	    	System.out.println("13 "+i);
    	    	String tbData[] = {p_id,p_name,p_price,add_quantity,Float.toString(sub_total[i])};
		    	DefaultTableModel tbModel = (DefaultTableModel)jTable2.getModel();
		    	tbModel.addRow(tbData);
		    	i++;
		    	System.out.println("14 "+i);
    			}}
    		else
    		{
    				JOptionPane.showMessageDialog(rootPane,"Enter valid product id");
    		}
    		}
    		
    	}
    	catch(Exception e)
    	{
    		JOptionPane.showMessageDialog(rootPane,"Could not fetch data from database \n Hint:- Check Product ID!!!");
    	}
    	}
    	else
    	{
    		JOptionPane.showMessageDialog(rootPane, "Please Login First");
    		get_frontpage();
    	}
    }//GEN-LAST:event_add_to_bill_btnActionPerformed

    private void total_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_textfieldActionPerformed
    
    
    
    //Arpits methods and classes
    
    public void reset_table()
    {
    	DefaultTableModel tMOdel = (DefaultTableModel) jTable2.getModel();
    	tMOdel.setRowCount(0);
    	total_textfield.setText(" ");
    }
    public void get_frontpage()
    {
    	Front_page fp=new Front_page();
    	fp.setVisible(true);
    	this.dispose();
    }
    class idquantity {
    	public String id;
    	public int quantity;
    	
    	// constructor
    	public idquantity(String id, int quantity) 
    	{
    		this.id = id;
    		this.quantity = quantity;
    	}
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill_board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill_board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill_board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill_board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Bill_board().setVisible(true);
        });
    }

  //Arpit's Variables
    String[][] ledger=new String[30][1];
    public float SUM=0;
    public static int i=1;
    public boolean print;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_to_bill_btn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton generate_bill_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel product_id_label;
    private javax.swing.JTextField product_id_textfield;
    private javax.swing.JLabel quantity_label;
    private javax.swing.JTextField quantity_textfield;
    private javax.swing.JLabel total_label;
    private javax.swing.JTextField total_textfield;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
