/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front_package.admin_frontpage;

import front_package.Front_page;
import front_package.admin_frontpage.view_report_inventory.view_report_inventory;
import front_package.login.login;
import front_package.pos_add_page.Pos_register_page;
import front_package.update_stocks.Update_stocks;
import front_package.view_pos.View_pos;
import java.awt.Insets;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import SRS.srs;

/**
 *
 * @author dell
 */
public class Admin_frontpage extends javax.swing.JFrame {

    /**
     * Creates new form pos_frontpage
     */
    public Admin_frontpage() {
        initComponents();
        setSize(1980, 1080);
        this.setResizable(true);
        this.setAlwaysOnTop(true);
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int)tk.getScreenSize().getWidth();
        int ysize = (int)tk.getScreenSize().getHeight();
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        this.setSize(xsize, ysize - taskBarSize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        view_report = new javax.swing.JButton();
        assign_new_pos = new javax.swing.JButton();
        view_report_inventory = new javax.swing.JButton();
        view_pos = new javax.swing.JButton();
        update_stocks1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        imagelabel=new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS Page");
        setIconImages(null);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255, 90));

        logout.setBackground(new java.awt.Color(153, 153, 153));
        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setText("Logout");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select Any Option");

        view_report.setBackground(new java.awt.Color(255, 230, 174));
        view_report.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        view_report.setText("Generate Reorder List");
        view_report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_reportActionPerformed(evt);
            }
        });

        assign_new_pos.setBackground(new java.awt.Color(255, 230, 174));
        assign_new_pos.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        assign_new_pos.setText("Assign New POS");
        assign_new_pos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        assign_new_pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assign_new_posActionPerformed(evt);
            }
        });

        view_report_inventory.setBackground(new java.awt.Color(255, 230, 174));
        view_report_inventory.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        view_report_inventory.setText("View Report Inventory");
        view_report_inventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view_report_inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_report_inventoryActionPerformed(evt);
            }
        });

        view_pos.setBackground(new java.awt.Color(255, 230, 174));
        view_pos.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        view_pos.setText("View POS");
        view_pos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view_pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_posActionPerformed(evt);
            }
        });

        update_stocks1.setBackground(new java.awt.Color(255, 230, 174));
        update_stocks1.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        update_stocks1.setText("Update Stocks");
        update_stocks1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_stocks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_stocks1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view_pos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update_stocks1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(assign_new_pos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(view_report_inventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 444, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addComponent(view_report, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assign_new_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_report, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_stocks1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_report_inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(130, 80, 1280, 610);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backdrop.jpg"))); // NOI18N
        jLabel1.setToolTipText("Admin-Page");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1980, 800);
        
        
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assign_new_posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assign_new_posActionPerformed
        // TODO add your handling code here:
      	if(login.LOGIN==1)
    	{
        if(evt.getSource() == assign_new_pos)
        {
            Pos_register_page vp = new Pos_register_page();
            vp.setVisible(true);
            vp.show();
            dispose();
        }
    	}
    	else
    	{
    		JOptionPane.showMessageDialog(rootPane,"Please Login First");
    		Front_page fp = new Front_page();
            fp.setVisible(true);
            dispose();
    	}
    }//GEN-LAST:event_assign_new_posActionPerformed

    private void view_posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_posActionPerformed
        // TODO add your handling code here:
    	if(login.LOGIN==1)
    	{
    	String url="jdbc:postgresql://localhost/POS_APP";
    	String user ="postgres";
    	String password="postgres";
    	View_pos vp1=new View_pos();
    		try(Connection con = DriverManager.getConnection( url,user,password);)
    		{
    			String sql="Select * from pos WHERE u_id IS NOT NULL";
    			Statement stmt1 = con.createStatement();
    		    ResultSet rs1=stmt1.executeQuery(sql);
    		    while(rs1.next())
    		    {
    		    	int pos_id=(rs1.getInt("p_id"));
    		    	String p_id=Integer.toString(pos_id);
    		    	String pos_name=(rs1.getString("name"));
    		    	String pos_m_no=(rs1.getString("m_no"));
    		    	//String address=(rs.getString("address"));
    		    	//int u_id=(rs1.getInt("u_id"));
    		    	String tbData[] = {p_id,pos_name, pos_m_no};
    		    	DefaultTableModel tbModel = (DefaultTableModel)vp1.jTable2.getModel();
    		    	tbModel.addRow(tbData);
    		    }
    		    con.close();
    		}
    		catch(Exception e)
    		{
    			
    		}
        if(evt.getSource() == view_pos)
        {
            vp1.setVisible(true);
            vp1.show();
            dispose();
        }
    }
    else
    	{
    		JOptionPane.showMessageDialog(rootPane,"Please Login First"); 
    		Front_page fp = new Front_page();
            fp.setVisible(true);
            dispose();
    	}
    }//GEN-LAST:event_view_posActionPerformed

    private void view_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_reportActionPerformed
    	if(login.LOGIN==1)
    	{
    		srs generate=new srs();
    		generate.run_srs();
    		JOptionPane.showMessageDialog(rootPane,"Reorder List Created at D:/reorderlist.csv");
    	}
    	else
    	{
    		JOptionPane.showMessageDialog(rootPane, "Please Login First");
    		Front_page fp = new Front_page();
            fp.setVisible(true);
            dispose();
    	}
    	// TODO add your handling code here:
       
    }//GEN-LAST:event_view_reportActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Logout Successfull");
        if(evt.getSource() == logout){
            Front_page fp = new Front_page();
            fp.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void view_report_inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_report_inventoryActionPerformed
        // TODO add your handling code here:
    	view_report_inventory vp = new view_report_inventory();
    	if(login.LOGIN==1)
    	{
    		
    	String url="jdbc:postgresql://localhost/POS_APP";
    	String user="postgres";
    	String password="postgres";
    	
    	String sql_select="Select * FROM inventory";
    	
    	try(Connection con=DriverManager.getConnection(url,user,password))
    	{
    		Statement stmt=con.createStatement();
    		ResultSet rs=stmt.executeQuery(sql_select);
    		while(rs.next())
    		{
    	    	String p_id=(rs.getString("id"));
    	    	String p_name=(rs.getString("name"));
    	    	String p_price=(Double.toString(rs.getDouble("price")));
    	    	String actual_quantity=(Integer.toString(rs.getInt("actual_quantity")));
    	    	String cat=rs.getString("category");
    	    	String tbData[] = {p_id,p_name,actual_quantity,p_price,cat};
		    	DefaultTableModel tbModel = (DefaultTableModel)vp.jTable1.getModel();
		    	tbModel.addRow(tbData);
    		}
    		if(evt.getSource() == view_report_inventory)
    		{
    			
    			vp.setVisible(true);
    			vp.show();
    			dispose();
    		}
    		con.close();
    	}
    	catch(Exception e)
    	{
    		JOptionPane.showMessageDialog(rootPane,"Could not fetch data from database \n Try Again!!!");
    	}
    	}
    	else
    	{
    		JOptionPane.showMessageDialog(rootPane, "Please Login First");
    		Front_page fp = new Front_page();
            fp.setVisible(true);
            dispose();
    	}
    }//GEN-LAST:event_view_report_inventoryActionPerformed

    private void update_stocks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_stocks1ActionPerformed
        
    	if(login.LOGIN==1)
    	{
        if(evt.getSource() == update_stocks1)
        {
            Update_stocks vp = new Update_stocks();
            vp.setVisible(true);
            vp.show();
            dispose();
        }
    	}
    	else
    	{
    		JOptionPane.showMessageDialog(rootPane,"Please Login First");
    		Front_page fp = new Front_page();
            fp.setVisible(true);
            dispose();
    	}
    	// TODO add your handling code here:
    }//GEN-LAST:event_update_stocks1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_frontpage().setVisible(true);
            }
        });
    }
    private javax.swing.JLabel imagelabel; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assign_new_pos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton update_stocks1;
    private javax.swing.JButton view_pos;
    private javax.swing.JButton view_report;
    private javax.swing.JButton view_report_inventory;
    // End of variables declaration//GEN-END:variables
}
