/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front_package.forgot_password;

import java.awt.Insets;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

import javax.swing.JOptionPane;

import front_package.Front_page;
import front_package.login.login;
import front_package.view_pos.View_pos;

/**
 *
 * @author dell
 */
public class Forgot_password extends javax.swing.JFrame {

    /**
     * Creates new form Forgot_password
     */
    public Forgot_password() {
        initComponents();
        setSize(1340, 820);
        this.setResizable(true);
        this.setAlwaysOnTop(true);
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int)tk.getScreenSize().getWidth();
        int ysize = (int)tk.getScreenSize().getHeight();
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        this.setSize(xsize, ysize - taskBarSize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	imagelabel=new javax.swing.JLabel();
    	
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        back = new javax.swing.JButton();
        id_label = new javax.swing.JLabel();
        mobile_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        confirm_pwd_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        enter_id_textfield = new javax.swing.JTextField();
        enter_mobile_textfield = new javax.swing.JTextField();
        enter_name_textfield = new javax.swing.JTextField();
        confirm_password_textfield = new javax.swing.JPasswordField();
        password_textfield = new javax.swing.JPasswordField();
        reset_password_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(163, 205, 160, 40));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Reset Your Password");

        logout.setBackground(new java.awt.Color(153, 153, 153));
        logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logout.setText("Logout");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setText("Back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        id_label.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        id_label.setText("Enter User ID");

        mobile_label.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        mobile_label.setText("Enter Mobile No");

        password_label.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        password_label.setText("Enter Password");

        confirm_pwd_label.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        confirm_pwd_label.setText("Confirm Password");

        name_label.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        name_label.setText("Enter Name");

        enter_id_textfield.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        enter_id_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        enter_id_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_id_textfieldActionPerformed(evt);
            }
        });

        enter_mobile_textfield.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        enter_mobile_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        enter_mobile_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_mobile_textfieldActionPerformed(evt);
            }
        });

        enter_name_textfield.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        enter_name_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        enter_name_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_name_textfieldActionPerformed(evt);
            }
        });

        confirm_password_textfield.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        confirm_password_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        confirm_password_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_password_textfieldActionPerformed(evt);
            }
        });

        password_textfield.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        password_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        password_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_textfieldActionPerformed(evt);
            }
        });

        reset_password_btn.setBackground(new java.awt.Color(153, 153, 153));
        reset_password_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reset_password_btn.setText("Reset Password");
        reset_password_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset_password_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_password_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(463, 463, 463)
                                .addComponent(reset_password_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(308, 308, 308)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(id_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mobile_label, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                        .addComponent(password_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(confirm_pwd_label, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(enter_mobile_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(confirm_password_textfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(enter_id_textfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(enter_name_textfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(password_textfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobile_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter_mobile_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(confirm_pwd_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(confirm_password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(reset_password_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(250, 120, 1070, 570);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 800);

        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backdrop.jpg"))); // NOI18N
        imagelabel.setPreferredSize(new java.awt.Dimension(1980, 1080));
getContentPane().add(imagelabel);
        imagelabel.setBounds(0, 0, 1980, 1080);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enter_id_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_id_textfieldActionPerformed
       
    	// TODO add your handling code here:
    }//GEN-LAST:event_enter_id_textfieldActionPerformed

    private void enter_mobile_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_mobile_textfieldActionPerformed
        
    	
    	// TODO add your handling code here:
    }//GEN-LAST:event_enter_mobile_textfieldActionPerformed

    private void enter_name_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_name_textfieldActionPerformed
        
    	
    	// TODO add your handling code here:
    }//GEN-LAST:event_enter_name_textfieldActionPerformed

    private void password_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_textfieldActionPerformed
    	
    	// TODO add your handling code here:
    }//GEN-LAST:event_password_textfieldActionPerformed

    private void confirm_password_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_password_textfieldActionPerformed
    	if(confirm_password_textfield.getText().isEmpty())
        {
        	JOptionPane.showMessageDialog(rootPane,"Password Cannot Be Blank");
        }
    	// TODO add your handling code here:
    }//GEN-LAST:event_confirm_password_textfieldActionPerformed

    private void reset_password_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_password_btnActionPerformed
    	String url="jdbc:postgresql://localhost/POS_APP";
    	String user ="postgres";
    	String password="postgres";
 
    	PreparedStatement psu=null,psac=null,pspc=null;
    	String sql_update="UPDATE login SET password=? WHERE u_id=?";
    	String checka="SELECT u_id from admin WHERE name=? and u_id=? and m_no=?";
    	String checkp="SELECT u_id from pos WHERE name=? and u_id=? and m_no=?";
        // var names as per the prepared statement parameter numbers
    	String name=enter_name_textfield.getText();
    	String mobile=enter_mobile_textfield.getText();
    	String id=(enter_id_textfield.getText());
    	String confirm_pwd=confirm_password_textfield.getText();

    	String pwd=password_textfield.getText();
    
    		try(Connection con = DriverManager.getConnection(url,user,password))
    		{
    		    
    			 if(enter_id_textfield.getText().isEmpty())
    		        {
    		        	JOptionPane.showMessageDialog(rootPane,"ID Cannot Be Blank");
    		        }
    			 else if(enter_mobile_textfield.getText().isEmpty())
    		        {
    		        	JOptionPane.showMessageDialog(rootPane,"Mobile number cannot be blank");
    		        }
    			 else if(enter_name_textfield.getText().isEmpty())
    		        {
    		        	JOptionPane.showMessageDialog(rootPane,"Name Cannot Be Blank");
    		        }
    			 else if(password_textfield.getPassword()==null)
    		        {
    		        	JOptionPane.showMessageDialog(rootPane,"Password Cannot Be Blank");
    		        }
    			 else {
    			 System.out.println(confirm_pwd+" "+pwd);
    			if(confirm_pwd.equals(pwd))
    			{
    			psac = con.prepareStatement(checka);
    			System.out.println("1");
    			psu= con.prepareStatement(sql_update);
    			System.out.println("2");
    			pspc= con.prepareStatement(checkp);
    			System.out.println("3");
    			psac.setString(1,name);
    			System.out.println("4");
    			psac.setInt(2,Integer.parseInt(id));
    			System.out.println("5");
    			psac.setString(3,mobile);
    			System.out.println("6");
    			pspc.setString(1,name);
    			System.out.println("7");
    			pspc.setInt(2,Integer.parseInt(id));
    			System.out.println("8");
    			pspc.setString(3,mobile);
    			System.out.println("9");
    			psu.setString(1,confirm_pwd);
    			System.out.println("10");
    			psu.setInt(2,Integer.parseInt(id));
    			System.out.println("11");
    			//validate database
    			if((pspc.execute() || psac.execute()))
    			{
    				if(psu.executeUpdate()!=0)
    				JOptionPane.showMessageDialog(rootPane, "Password Updated SUCCESSFULLY");
    			}
    			}
    			 else
    			 {
    				 JOptionPane.showMessageDialog(rootPane, "Password Mismatch\n Try Again");
    				 password_textfield.setText("");
    				 confirm_password_textfield.setText("");
    			 }
    			 }
    			 }
    		catch(Exception e)
    		{
    			
    			JOptionPane.showMessageDialog(rootPane,"Sorry!!! \n Your Personal Details Do Not Match");
    		}
    		
    	
    	// TODO add your handling code here:
    }//GEN-LAST:event_reset_password_btnActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    	if(evt.getSource() == back){
            login lg = new login();
            lg.setVisible(true);
            dispose();
    	}
    	// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
    	JOptionPane.showMessageDialog(rootPane, "Logout Successfull");
        if(evt.getSource() == logout){
            Front_page fp = new Front_page();
            fp.setVisible(true);
            dispose();
        }
    	// TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot_password().setVisible(true);
            }
        });
    }
    private javax.swing.JLabel imagelabel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JPasswordField confirm_password_textfield;
    private javax.swing.JLabel confirm_pwd_label;
    private javax.swing.JTextField enter_id_textfield;
    private javax.swing.JTextField enter_mobile_textfield;
    private javax.swing.JTextField enter_name_textfield;
    private javax.swing.JLabel id_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel mobile_label;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel password_label;
    private javax.swing.JPasswordField password_textfield;
    private javax.swing.JButton reset_password_btn;
    // End of variables declaration//GEN-END:variables
}
