/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front_package.pos_add_page;

import front_package.Front_page;
import front_package.admin_frontpage.Admin_frontpage;
import front_package.login.login;
import front_package.view_pos.View_pos;

import java.awt.Insets;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class Pos_register_page extends javax.swing.JFrame {

    /**
     * Creates new form Pos_register_page
     */
    public Pos_register_page() {
        initComponents();
        setSize(1340, 820);
        this.setResizable(true);
        this.setAlwaysOnTop(true);
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int)tk.getScreenSize().getWidth();
        int ysize = (int)tk.getScreenSize().getHeight();
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        this.setSize(xsize, ysize - taskBarSize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	imagelabel=new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        enter_pwd = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        enter_posid = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        phone_no = new javax.swing.JTextField();
        p_id = new javax.swing.JTextField();
        pos_name = new javax.swing.JTextField();
        paddress = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        user_id = new javax.swing.JTextField();
        u_id = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        add_pos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS-REGISTRATION PAGE");
        setBackground(new java.awt.Color(51, 255, 255));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(212, 211, 207, 70));
        jPanel2.setAlignmentX(0.0F);

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setText("Back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(153, 153, 153));
        logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logout.setText("Logout");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("POS Registration ");

        enter_pwd.setFont(new java.awt.Font("Meiryo UI", 1, 16)); // NOI18N
        enter_pwd.setText("Confirm Password");

        address.setFont(new java.awt.Font("Meiryo UI", 1, 16)); // NOI18N
        address.setText("Enter Address");

        enter_posid.setFont(new java.awt.Font("Meiryo UI", 1, 16)); // NOI18N
        enter_posid.setText("Enter Password");

        phone.setFont(new java.awt.Font("Meiryo UI", 1, 16)); // NOI18N
        phone.setText("Enter Phone Number");

        name.setFont(new java.awt.Font("Meiryo UI", 1, 16)); // NOI18N
        name.setText("Enter POS Name");

        phone_no.setFont(new java.awt.Font("Meiryo UI", 1, 16)); // NOI18N

        p_id.setFont(new java.awt.Font("Meiryo UI", 1, 16)); // NOI18N

        pos_name.setFont(new java.awt.Font("Meiryo UI", 1, 16)); // NOI18N

        paddress.setFont(new java.awt.Font("Meiryo UI", 1, 16)); // NOI18N

        pass.setFont(new java.awt.Font("Meiryo UI", 1, 16)); // NOI18N

        user_id.setFont(new java.awt.Font("Meiryo UI", 1, 16)); // NOI18N

        u_id.setFont(new java.awt.Font("Meiryo UI", 1, 16)); // NOI18N
        u_id.setText("Enter UserID");

        reset.setBackground(new java.awt.Color(153, 153, 153));
        reset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reset.setText("RESET");
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        add_pos.setBackground(new java.awt.Color(153, 153, 153));
        add_pos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add_pos.setText("ADD POS");
        add_pos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(u_id, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enter_posid, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enter_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(add_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(paddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(user_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(46, 46, 46)
                                    .addComponent(phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(46, 46, 46)
                                    .addComponent(pos_name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 390, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(321, 321, 321)
                                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos_name, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paddress, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter_posid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(160, 80, 1200, 640);

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1340, 740);

        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backdrop.jpg"))); // NOI18N
        imagelabel.setPreferredSize(new java.awt.Dimension(1980, 1080));
getContentPane().add(imagelabel);
        imagelabel.setBounds(0, 0, 1980, 1080);
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	phone_no.setText(" ");
        p_id.setText(" ");
        pos_name.setText(" ");
        paddress.setText(" ");
        pass.setText(" ");
        user_id.setText(" ");
    	// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    	if(login.LOGIN==1)
    	{
    	String url="jdbc:postgresql://localhost/POS_APP";
    	String user ="postgres";
    	String password="postgres";
    	View_pos vp=new View_pos();
    	PreparedStatement psd=null,psv=null,psl=null;
    	String sql_login="INSERT INTO login VALUES(?,?,'POS')";
    	String sql="INSERT INTO pos values(?,?,?,?,?)";
    	String delete="DELETE FROM login WHERE u_id=?";
        // var names as per the prepared statement parameter numbers
    	String two=pos_name.getText();
    	String three=phone_no.getText();
    	String four=paddress.getText();
    	int flag=1;
    		try(Connection con = DriverManager.getConnection(url,user,password))
    		{
    		    
    			if(p_id.getText()==null && user_id.getText()==null && three.length()!=10 && (pass.getText()).length()<4)
    				{
    				flag=0;
    				JOptionPane.showMessageDialog(rootPane,"All Fields are mandatory");
    				}
    			else if(three.length()!=10 && (pass.getText()).length()<4 && flag==1)
    			{
    				flag=0;
    				JOptionPane.showMessageDialog(rootPane,"Check Mobile No/Password");
    			}
    			else if(three.length()!=10 && flag==1)
    			{
    				flag=0;
    				JOptionPane.showMessageDialog(rootPane,"Mobile no must be 10 digits long");
    			}
    			else if((pass.getText()).length()<4 && flag==1)
    			{
    				flag=0;
    				JOptionPane.showMessageDialog(rootPane,"Password too short");
    			}
    			if(flag==1)
    			{
    			psv = con.prepareStatement(sql);
    			psl= con.prepareStatement(sql_login);
    			psv.setInt(1,Integer.parseInt(p_id.getText()));
    			psl.setInt(1,Integer.parseInt(user_id.getText()));
    			psv.setString(2,two);
    			psv.setString(3,three);
    			psv.setString(4,four);
    			psv.setInt(5,Integer.parseInt(user_id.getText()));
    			psl.setString(2,pass.getText());
    			//System.out.println("1");
    			
    			//validate database
    			if(psl.executeUpdate()!=0 && psv.executeUpdate()!=0)
    			{
    				flag=0;
    				JOptionPane.showMessageDialog(rootPane, "POS REGISTERED SUCCESSFULLY");
    			}
    			}
    		}
    		catch(Exception e)
    		{
    			
    			JOptionPane.showMessageDialog(rootPane,"Error in input data");
    		}
    	}
    	else
    	{
    		JOptionPane.showMessageDialog(rootPane,"Please Login First");
    		Front_page fp = new Front_page();
            fp.setVisible(true);
            dispose();
    	}
    	// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    	if(login.LOGIN==0)
    	{
    		Front_page fp=new Front_page();
    		fp.setVisible(true);
    		dispose();
    		JOptionPane.showInternalMessageDialog(rootPane,"Please Login First");
    		
    	}
    	else if(evt.getSource() == back)
        {
            Admin_frontpage vp = new Admin_frontpage();
            vp.setVisible(true);
            vp.show();
            dispose();
        }
    }//GEN-LAST:event_backActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    	JOptionPane.showMessageDialog(rootPane, "Logout Successfull");
        if(evt.getSource() == logout){
            Front_page fp = new Front_page();
            fp.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
    	
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pos_register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pos_register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pos_register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pos_register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pos_register_page().setVisible(true);
            }
        });
    }

    private javax.swing.JLabel imagelabel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton reset;
    private javax.swing.JButton add_pos;
    private javax.swing.JButton logout;
    
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel enter_pwd;
    private javax.swing.JLabel address;
    private javax.swing.JLabel enter_posid;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel name;
    private javax.swing.JLabel u_id;
    
    private javax.swing.JPanel jPanel2;
    
    private javax.swing.JTextField phone_no;
    private javax.swing.JTextField user_id;
    private javax.swing.JTextField pos_name;
    private javax.swing.JTextField paddress;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField p_id;
    // End of variables declaration//GEN-END:variables
}
