/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front_package.view_pos;

import front_package.Front_page;
//import front_package.pos_add_page.Pos_register_page;
import front_package.admin_frontpage.Admin_frontpage;
import front_package.login.login;
import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;

/**
 *
 * @author AAA
 */
public class View_pos extends javax.swing.JFrame {

    /**
     * Creates new form View_pos
     */
    public View_pos() {
        initComponents();
       
        setSize(1340, 820);
        this.setResizable(true);
        this.setAlwaysOnTop(true);
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int)tk.getScreenSize().getWidth();
        int ysize = (int)tk.getScreenSize().getHeight();
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        this.setSize(xsize, ysize - taskBarSize);
       
        //setBackground(new Color(0, 0, 0, 0));
        jTable2.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        jTable2.getTableHeader().setOpaque(false);
        jTable2.getTableHeader().setBackground(new Color(204, 204, 255));
        jTable2.getTableHeader().setForeground(new Color(0, 0, 0));
        jTable2.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	imagelabel=new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        delete_pos_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255, 90));
        jPanel1.setMinimumSize(new java.awt.Dimension(1, 1));

        logout.setBackground(new java.awt.Color(153, 153, 153));
        logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logout.setText("Logout");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setText("Back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("Displaying POS Details");

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "POS ID", "POS Name", "POS Phone Number"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(153, 153, 153));
        jTable2.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable2.setRowHeight(30);
        jTable2.setSelectionBackground(new java.awt.Color(204, 255, 204));
        jTable2.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTable2);

        delete_pos_btn.setBackground(new java.awt.Color(153, 153, 153));
        delete_pos_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delete_pos_btn.setText("Delete POS");
        delete_pos_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_pos_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_pos_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(214, 214, 214))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(151, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_pos_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)))
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete_pos_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(205, 80, 1130, 630);

        jLabel1.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 780);

        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backdrop.jpg")));
        imagelabel.setPreferredSize(new java.awt.Dimension(1980,1080));
        getContentPane().add(imagelabel);
        
        imagelabel.setBounds(0,0,1980,1080);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == back)
        {
            Admin_frontpage vp = new Admin_frontpage();
            vp.setVisible(true);
            vp.show();
            dispose();
        }
    }//GEN-LAST:event_backActionPerformed
    
    
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(rootPane, "Logout Successfull");
        if(evt.getSource() == logout){
            Front_page fp = new Front_page();
            fp.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void delete_pos_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_pos_btnActionPerformed
    	if(login.LOGIN==1)
        {
        	String url="jdbc:postgresql://localhost/POS_APP";
	    	String user="postgres";
	    	String password="postgres";
	    	PreparedStatement ps=null,stmt=null;
	    	String sql_d="DELETE FROM login WHERE u_id=?";
	    	String getuid="SELECT u_id FROM pos WHERE p_id=?";
	    	int userid = 0;
	    	ResultSet rs=null;
	    	try(Connection con=DriverManager.getConnection(url,user,password))
	   		{
	    		int row=jTable2.getSelectedRow();
	    		if(row==-1)
	    		{
	    			JOptionPane.showMessageDialog(rootPane,"Please select a record to delete");
	    		}
	    		else
	    		{
	    			int posid=Integer.parseInt(jTable2.getValueAt(row,0).toString());
	    			ps=con.prepareStatement(getuid);
	    			stmt=con.prepareStatement(sql_d);
	    			ps.setInt(1, posid);
	    			rs=ps.executeQuery();
	    			while(rs.next())
	    			{
	    				userid=rs.getInt("u_id");
	    			}
	    		stmt.setInt(1,userid);
	    		if(stmt.executeUpdate()!=0)
	    		{
	    			DefaultTableModel tbModel = (DefaultTableModel)jTable2.getModel();
	    			JOptionPane.showMessageDialog(rootPane, "POS Deleted Successfully");
	    			tbModel.removeRow(row);
	    			
	    		}
	    		else
	    		{
	    			JOptionPane.showMessageDialog(rootPane,"Error \n Try Again");
	    		}
	    		//System.out.println("1");
	    		con.close();
	    		}
	   		}
	    	catch(Exception e)
	    	{
	    		JOptionPane.showMessageDialog(rootPane, "Error");
	    		System.out.println(e.getLocalizedMessage());
	    	}
        }
        else
        {
        	JOptionPane.showMessageDialog(rootPane, "Please Login First");
    		Front_page fp = new Front_page();
            fp.setVisible(true);
            dispose();
        }
        
    	// TODO add your handling code here:
    }//GEN-LAST:event_delete_pos_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_pos().setVisible(true);
            }
        });
    }
    private javax.swing.JLabel imagelabel; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    public javax.swing.JButton delete_pos_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable2;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
